// <auto-generated />
namespace TFI.AccesoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pagos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pagos));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181637187_pagos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
